# Generated by Django 4.0.4 on 2023-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already exist'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
